<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div
    {
        MARGIN-RIGHT: auto;
        MARGIN-LEFT: auto; 
    }

    div#welcome
    {
        margin:100 auto;
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  800px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
}

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }

    .highlight
    {
        background:#439;
        cursor:pointer;
    }

    p
    {
        MARGIN-RIGHT: auto;
        MARGIN-LEFT: auto; 
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">网站信息查询工具siteQuery</span></h1>

    <h3>siteQuery提供网站SEO信息查询、网站ipwhois查询，网站注册备案查询</h3>

    <div id="info-query" >
        <form action="http://www.site-query.cn/sitequery/index" method="GET" >
            请输入域名:
            <input id="query-site" type="text" name="query-site" value="http://" /> 
            <p id="" >
                <input type="checkbox" name="querys[]" value="host-query" /><span class="highlight"> 主机信息</span>  <!-- 主机信息查询 -->
                <input type="checkbox" name="querys[]" value="seo-query" /><span class="highlight"> SEO信息</span> <!-- SEO信息查询 -->
                <input type="checkbox" name="querys[]" value="ipwhois-query" /><span class="highlight"> ipwhois</span> <!--ipwhois 查询  -->
              <!--  <input type="checkbox" name="querys[]" value="record-query" /><span class="highlight"> 网站备案</span>  网站注册备案查询-->
            </p>
            <p>
                <input style="cursor:pointer" type="submit" name="submit" value="查询" /> 
            </p>
            
        </form>
    </div>
    <div id="more-information">
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>
